### ISSUE TITLE
Add support for override_settings

### ISSUE THREAD

**Issue by ziima** [Genida/django-appsettings#16]
Settings defined by `appsettings` can't be changed by `override_settings` in tests.

```python
from django.test import override_settings

from my_app.settings import MySettings

app_conf = MySettings()
print app_conf.CUSTOM_SETTING  # 'custom_value'
with override_settings(CUSTOM_SETTING='another'):
    print app_conf.CUSTOM_SETTING  # 'custom_value'!
```

**Comment by Pawamoy** [comment]
It's because you already instantiated your settings with `app_conf = MySettings`.

Try this instead:

```
from django.test import override_settings

from my_app.settings import MySettings

app_conf = MySettings()
print app_conf.CUSTOM_SETTING  # 'custom_value'
with override_settings(CUSTOM_SETTING='another'):
    print MySettings.CUSTOM_SETTING.get()  # should be 'another'
```

**Comment by ziima** [comment]
I end up with an error: `AttributeError: 'str' object has no attribute 'get'`

**Comment by Pawamoy** [comment]
Can you show me your `MySettings` class?

**Comment by ziima** [comment]
Sorry about that, here's a full example
```
from django.test import override_settings
from appsettings import AppSettings, StringSetting

class MySettings(AppSettings):
    CUSTOM_SETTING = StringSetting(default='custom_value')

    class Meta:
        setting_prefix = 'MY_'

app_conf = MySettings()
print app_conf.CUSTOM_SETTING.get()
with override_settings(MY_CUSTOM_SETTING='another'):
    print app_conf.CUSTOM_SETTING.get()
```

**Comment by Pawamoy** [comment]
Alright, I will update the README so people don't get confused:

- if you instantiate `MySettings` class as `app_conf`, all settings are loaded as attributes of the instance (`app_conf.CUSTOM_SETTING` has type `str`)
- in tests, or if you want to get the settings dynamically, you must call the class attribute directly: `MySettings.CUSTOM_SETTING.get()` (not `app_conf.CUSTOM_SETTING.get()` since it's already loaded as a string, not a `Setting` object)

**Comment by ziima** [comment]
OK, now it's clear, but I kind of undermines the usability of the appsettings. We want the simple usage of the settings in code, i.e. `.CUSTOM_SETTING`, and the ability to use the `override_settings` in tests (it may require to bind a callback to `settings_changed` signal). Any chance to see such a change?

**Comment by Pawamoy** [comment]
What you can do is the following:

```python
with override_settings(MY_CUSTOM_SETTING='another'):
    app_conf = MySettings()
    print app_conf.CUSTOM_SETTING  # print 'another'
```

I understand that it would be nice to declare `app_conf = MySettings()` only once, at the beginning of the test file, and use `app_conf` in the tests functions. We could use the settings the same way in code and in tests.

To be able to do so, instantiating an `AppSettings` object should return an object with settings attributes being **properties**. These properties would do the exact same thing as `AppSettings.my_setting.get()`, it means fetching the value from the current Django settings. But it also means more time and processing to access it (though in general we just use simple types for settings).

Suppose you have a critical function in your code that uses one of your settings. The setting is the Python path to an object. The function is called thousands of time during execution. Each time it is called, the setting is fetched and transformed, meaning the object is actually imported each time the function is called. It the setting transformation is even more complex, it will cost again more CPU / time at each function call. 

I didn't do any benchmarking on this, so maybe what I'm saying has no real impact. And I agree with what you want.

Maybe we could reverse the process: by default, accessing a setting is done through a property (so it would work the same way in both code and tests), and if you have performance issue, you can still call a `preload` method in critical parts of your code to fetch and transform, once and for all, one or every settings.

What do you think? Do you have different ideas on how to achieve this?

This app is still alpha so I don't mind changing things a bit. Also open to PRs (on a separated branch) :D !

**Comment by ziima** [comment]
We have a similar mechanism for our settings at the moment, which I'd like to deprecated in favor of appsettings. We actually use `__getattr__` to retrieve the settings (though properties might be more readable), but it caches their values in the settings instance. Thus, each subsequent access only returns the cached value and skips whatever process was required to get the value. To allow `override_settings` to work in tests, we have a `clean_cache` method, which is bound to `settings_changed` signal, so every time the settings change in tests, the cache is dropped and settings are reloaded.

So what about caching the settings in the `AppSettings` instance?

**Comment by Pawamoy** [comment]
So the idea would be to implement properties + caching + cache invalidation on `setting_changed` signal, in this app, am I right?

I read on https://docs.djangoproject.com/en/1.11/ref/signals/#module-django.test.signals that the signal is `sent only when running tests`. But I also notice `You can also import this signal from django.core.signals to avoid importing from django.test in non-test situations.` which is a bit contradictory. I usually run my tests without `./manage.py test` command, just feeding the test directory to pytest instead (**without** pytest-django plugin). Would this still work?

I can work on the properties + caching part, would you like to send a PR (once I'm done) to add the cache invalidation feature (since you already experienced with it)? Or maybe provide me some example code to see how you implemented it?

**Comment by ziima** [comment]
> properties + caching + cache invalidation 

Agreed 👍 

Ad `setting_changed`: Looking at the code, the signal is actually defined in `django.core.signals` and imported into `django.test`, so it works both ways. Looking at the code, it's triggered by the `override_settings` or `TestCase`, which is the reason why it should only by called from tests.

Since I run my tests using `./manage.py test` command, I'm not sure, how it will behave under pytest, but I don't expect any troubles.

I can definitely help you with the changes. If you're going to do the properties, let me know when you're done.

**Comment by Pawamoy** [comment]
Alright thank you! I'm actually using `__getattr__` just as you do, because properties are way too complicated to generate dynamically (they are attributes of the class, not the instance, therefore instantiating the class would modify the class, it's a hell).

I'm almost done. I refactored the settings module as well (less generators, more explicit, more class inheritance, easier to debug).

Code will look like this:

```python
import appsettings as aps

class MySettings(aps.AppSettings):
    setting1 = aps.Setting(default='hello')

# can't call setting from class anymore, as it would prevent entering __getattr__ in instances
MySettings.setting1
# AttributeError: type object 'MySettings' has no attribute 'setting1'
# maybe we can look at how django deals with this

my_settings = MySettings()

print(my_settings.setting1)  # hello

my_settings.invalidate_cache()

with override_settings(SETTING1='world'):
    print(my_settings.setting1)  # world
```

**Comment by Pawamoy** [comment]
Ok, new branch is `refactor-properties-caching`

**Comment by Pawamoy** [comment]
I managed to make the settings objects available again from the class:

```python
MySettings.setting1  # <appsettings.settings.Setting at 0x7ff71c63b358>
my_settings.setting1  # 'hello'
```

See commit https://github.com/Genida/django-appsettings/commit/0ff7f4c45c04f2ae5cf1e0960dd8320fd756436f

**Comment by ziima** [comment]
Nice work 👍 

I'll have a look and if I have further improvements, I'll create a PR. The README should be updated though.

**Comment by Pawamoy** [comment]
Yes, README and CHANGELOG will need updates, but we can do this after the hard work is done :)

**Comment by ziima** [comment]
To allow `invalidate_cache` to be used as a signal receiver, it must accept `**kwargs`.
```python
from django.core.signals import setting_changed
setting_changed.connect(my_settings.invalidate_cache) 
# ValueError: Signal receivers must accept keyword arguments (**kwargs).
```

**Comment by Pawamoy** [comment]
OK, feel free to modify where it is needed :)

**Comment by ziima** [comment]
Sorry for late reply. `**kwargs` is sufficient change.

Automatic connection to the signal is good idea. I don't see any drawbacks. Although, I'd recommend using the dispatch ID.

**Comment by Pawamoy** [comment]
So a simple line like

```python
setting_changed.connect(self.invalidate_cache, dispatch_uid=id(self))
```

in AppSettings `__init__` method should suffice then!

**Comment by ziima** [comment]
Damn, you're fast 👍 

I have one concern: If the access to the settings work through both, the class and the instance, the signal will not get connected in projects where the settings are only accessed through the `AppSettings` class and the `__init__` will never be called. Do I understand correctly the the class access is not cached? I that case, everything's fine.

**Comment by Pawamoy** [comment]
You are right, values are not cached when accessing them from the class itself.

```python
AppConf.setting.value  # never cached, no signal connected
appconf.setting  # cached, invalidated on signal reception
```

As said in issue #17, I will update README, CHANGELOG and docs as soon as possible and bump the version to 1.0.0.

**Comment by Pawamoy** [comment]
Release version 0.3.0 :)
