### ISSUE TITLE
Generic ListSetting

### ISSUE THREAD

**Issue by stinovlas** [Genida/django-appsettings#50]
I often need to create a setting containing list of objects. For example, I want a list of dotted paths to callables. Or I want a list of dotted paths to classes, which are all subclasses of a given ancestor. Or I want a list of file paths.

It would be great, if I wouldn't have to create `CallableListSetting`, `ObjectListSetting` or `FileListSetting`, but could simply use some kind of **list container** that would take my normal flat `CallableSetting`, `ObjectSetting` or `FileSetting` as its argument and that would validate each of list items by validators defined by that specific flat setting.

I'm not yet sure about the syntax we should use. I'd prefer to hear some comments first.

**Comment by pawamoy** [comment]
Indeed it would be quite useful. Can you paste an example of your implementation of ObjectListSetting or FileListSetting, just to see? Along with the actual setting in `settings.py` of course?

**Comment by pawamoy** [comment]
In fact, it could be done with new validators:

```python
def import_object(path):
    ...


class ObjectPathValidator:
    def __call__(self, value):
        try:
            obj = import_object(value)
        except ImportError:
            raise ValidatiorError


class CallablePathValidator:
    def __call__(self, value):
        try:
            obj = import_object(value)
        except ImportError:
            raise ValidationError
        if not callable(obj):
            raise ValidatiorError


class ValuesObjectPathValidator:
    def __call__(self, value):
        validate = ObjectPathValidator()
        for element in value:
            validate(value)


class ValuesCallablePathValidator:
    def __call__(self, value):
        validate = CallablePathValidator()
        for element in value:
            validate(value)
```

```python
import appsettings as aps

callable_list = aps.ListSetting(validators=[aps.ValuesCallablePathValidator()])
```

In fact we could refactor the values validators to accept other validators:

```python
class ValuesValidator:
    message = "Element %(value)s is not of type %(type)s."

    def __init__(self, validator, message=None):
        self.validate = validator
        if message:
            self.message = message

    def __call__(self, value):
        for element in value:
            self.validate(value)


# our previous ValuesTypeValidator would become:
class ValuesTypeValidator:
    def __init__(self, value_type, message=None):
        self.value_type = value_type
        if message:
            self.message = message

    def __call__(self, value):
        validate = TypeValidator(self.value_type)
        for element in value:
            validate(value)

# both lines are equivalent
setting = Setting(validators=[ValuesValidator(TypeValidator(str))]
setting = Setting(validators=[ValuesTypeValidator(str)]
```

What do you think?

**Comment by ziima** [comment]
I'm more in favor of making `ListSetting` similar to `NestedSetting`, where the outer setting is a container for other `Setting` objects. I provides other features of the internal type, not only the validation itself.

**Comment by stinovlas** [comment]
Well, as @ziima said, it's not only about validation. Transformation is important as well.

E.g. I have this simple setting:

```python
class CallableListSetting(appsettings.ListSetting):
    """
    Callable list setting.

    Contains list of dotted paths refering to callables.
    """

    def __init__(self, *args, **kwargs):
        """Ensure that list items are strings."""
        kwargs['item_type'] = str
        super().__init__(*args, **kwargs)

    def transform(self, value):
        """Translate dotted path to callable."""
        return [module_loading.import_string(call) for call in value]

    def validate(self, name, value):
        """Check whether dotted path refers to callable."""
        transformed_value = self.transform(value)
        for call in transformed_value:
            if not callable(call):
                raise ValueError('{} must be a list of dotted paths to callables'.format(name))
```

So, I transform each of the list values and I also validate each of them separately.

**Comment by pawamoy** [comment]
Ah yes, I forgot you still need the transformation.

Then if we go with combination of settings (which seems to be the obvious choice since we already have `NestedSetting` indeed), then maybe we should have this:

- `NestedSetting` renamed `NestedDictSetting`
- make `NestedSetting` point to `NestedDictSetting` for backward-compatibility
- create `NestedListSetting` instead of modifying `ListSetting` (just like what we already have: `DictSetting` and it's nested equivalent `NestedSetting`)

**Comment by stinovlas** [comment]
>    * `NestedSetting` renamed `NestedDictSetting`
>    * make `NestedSetting` point to `NestedDictSetting` for backward-compatibility
>    * create `NestedListSetting` instead of modifying `ListSetting` (just like what we already have: `DictSetting` and it's nested equivalent `NestedSetting`)

Could be. Of course, there can be only one type of nested setting inside the `NestedListSetting`. Otherwise we wouldn't know which one of the transformation (and validation) methods should be used.

**Comment by pawamoy** [comment]
Of course. Do you want to open a PR with these modifications?

**Comment by stinovlas** [comment]
I'll try to put something together.
