### ISSUE TITLE
Request for maintainer access

### ISSUE THREAD

**Issue by ziima** [Genida/django-appsettings#63]
With @stinovlas we agree to accept the maintainer access to both github and pypi.

**Comment by pawamoy** [comment]
Could you please give me your usernames on PyPI?

**Comment by stinovlas** [comment]
> Could you please give me your usernames on PyPI?

Sure, my username is `jan-musilek` and @ziima has username `ziima`.

**Comment by pawamoy** [comment]
Done!

**Comment by ziima** [comment]
Thanks :-)
